services:
  app:
    build: .
    container_name: fastapi-mqtt-app
    environment:
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      DMI_API_KEY: ${DMI_API_KEY}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
      EXPO_PUSH_TOKEN: ${EXPO_PUSH_TOKEN}
      MQTT_BROKER: ${MQTT_BROKER}
    ports:
      - "8111:8000"
    env_file:
      - .env
    restart: unless-stopped